### PR TITLE
add code-format

### PR DESCRIPTION
**Pull request by asukaminato0721**
Now it works well when **kernel is connected** and format **one cell** at a time.

---

Currently, function `formatString` is ~~pending to be~~ finished. I find https://github.com/WolframResearch/codeformatter may work, but couldn't figure out how to make this api.

Reference:

https://code.visualstudio.com/blogs/2016/11/15/formatters-best-practices#_the-formatting-api

### CODE REVIEW

**Comment by wuyudi** [comment]
```ts
const fs = require("fs");
const path = require("path")
const os = require("os")
const { execSync } = require('child_process');
fs.writeFileSync(path.join(os.homedir(), "tmp.wls"), "Plot[ Sin[x],   {x,0,5}]")
console.log( execSync('wolframscript -file ~/proxy.wls').toString())
```

~/proxy.wls

```mma
Needs["CodeFormatter`"];
CodeFormat[File["~/tmp.wls"]] // WriteString[Streams["stdout"], #]&
```

Currently, this code work on NodeJS. But when I put it in plugin.

> The editor could not be opened due to an unexpected error: Cannot open resource with notebook editor type 'wolfram-language-notebook', please check if you have the right extension installed and enabled.

Maybe I need to use zmq to communicate with wolframscript.

**Comment by wuyudi** [comment]
After some test, I made this work.

https://github.com/Vap0r1ze/mathematica.js

```js
const { MathematicaKernel } = require("mathematica.js");


const query = "a[b[c[d,e,f,g,\"5\"]]] // f // g // h";
const mathKernel = new MathematicaKernel()
const utf8_to_b64 = (s) => Buffer.from(s).toString('base64');
// mathKernel.run(query: string, expectResult: boolean)
mathKernel.run('Needs["CodeFormatter`"]', false);

mathKernel.run(`"${utf8_to_b64(query)}" // BaseDecode // ByteArrayToString // CodeFormat`).then(result => {
    console.log(result.toString())
  })


setTimeout(() => {
  mathKernel.destroy()
}, 4000)
```

**Comment by wuyudi** [comment]
Seems that vscode has some problem with child_process

```ts
import { MathematicaKernel } from "mathematica.js";
const formatString = async (s: string) => {
    const ans = "1";
    const output = vscode.window.createOutputChannel("CodeFormatter");
    const log = output.appendLine;
    log(`[${new Date().toUTCString()}] code waited for formatting ${s}`);
    const utf8_to_b64 = (s: string) => Buffer.from(s).toString('base64');
    // const mathKernel = new MathematicaKernel();  <----- if remove comment, this plugin stops working.
    log("init kernel");
    // mathKernel.run('Needs["CodeFormatter`"]', false);
    // log("init pkg");
    // const ans = (await mathKernel.run(`"${utf8_to_b64(s)}" // BaseDecode // ByteArrayToString // CodeFormat`)).toString();
    // log("get result");
    // mathKernel.destroy();
    // log("remove kernel");
    return ans;
};
```

**Comment by wuyudi** [comment]
tmp lack of time, closed.

**Comment by wuyudi** [comment]
current progress, I can see the result from `logWrite`

```mma
[Thu, 03 Aug 2023 00:03:12 GMT] Received the following data from kernel:
[Thu, 03 Aug 2023 00:03:12 GMT] Manipulate[
Block[{a=1.,n=8,θ=Pi/(2 n),e=Cos[θ],b=a Sin[θ]},
Graphics[{
Circle[{0,0},{a,b}],
Table[{If[Sin@#>Sin[θ],Circle[{-a Cos[θ] Cos[#],0},a Sin[θ] Sin[#]]]&/@
{2 i θ+t,t-2 (i-1) θ}},{i,n-1}]
},PlotRange->1.1a]
],{t,0,Pi/2}]
[Thu, 03 Aug 2023 00:03:12 GMT] Received the following data from kernel:
[Thu, 03 Aug 2023 00:03:12 GMT] Manipulate[
    Block[{a = 1., n = 8, θ = Pi / (2 n), e = Cos[θ], b = a Sin[θ]},
        Graphics[
            {
                Circle[{0, 0}, {a, b}]
                ,
                Table[
                    {
                        If[Sin @ # > Sin[θ],
                                Circle[{-a Cos[θ] Cos[#], 0}, a Sin[θ
                                    ] Sin[#]]
                            ]& /@ {2 i θ + t, t - 2 (i - 1) θ}
                    }
                    ,
                    {i, n - 1}
                ]
            }
            ,
            PlotRange -> 1.1 a
        ]
    ]
    ,
    {t, 0, Pi / 2}
]
[Thu, 03 Aug 2023 00:03:12 GMT] Failed to parse the following message:
[Thu, 03 Aug 2023 00:03:12 GMT] StringToByteArray[$Failed]
```

**Comment by wuyudi** [comment]
https://github.com/njpipeorgan/wolfram-language-notebook/assets/30024051/55cc604b-a8d4-4fb1-aa3c-89a61a1a92c2

**Comment by asukaminato0721** [comment]
https://github.com/asukaminato0721/mmafmt

**Pull request closed without merging**
