### PR TITLE
add dynamic by wolfram player

### LINKED ISSUE #40: Add dynamic plot3d
**Is your feature request related to a problem?**
A clear and concise description of what the problem is.

Now 3d plot is static. Make them interactive.

**Describe the solution you'd like**

https://github.com/wuyudi/Mathematica-ThreeJS-graphics-engine/tree/enable-plot3d

```mma
Plot3D[Sin[x^2+y^2], {x,0,4},{y,0,4}] 
%//ExportString[#//N, "ExpressionJSON"]& // Export["~/test.txt", #]&
```

now it works well

image

**Additional context**

Some pitfalls:

Because that repo is legacy, three js's version is old, hard to add new functions.

For example:

https://stackoverflow.com/a/51591365

https://discourse.threejs.org/t/three-geometry-will-be-removed-from-core-with-r125/22401

### PR DESCRIPTION
**Pull request by asukaminato0721**
fix https://github.com/njpipeorgan/wolfram-language-notebook/issues/40

This is a prototype, still has some problems. But it works well now.

Player is distributed with Engine, so it's ok to use it.

Some remaining TODOs:

1. set the wolfram player path in config. (Didn't figure out how to do it). Currently I hard coded it.
2. if using `StartProcess` , when close the player window, it will
      ```
      Received the following data from kernel (stderr):
      [Mon, 31 Jul 2023 16:06:46 GMT] terminate called after throwing an instance of 'zmq::error_t'
        what():  Interrupted system call
      ```
      I don't know how to fix it, so I use `Run`, but `Run` will stuck the notebook, so I add `&` to avoid it. (But I don't know whether it's ok on windows).

     And I don't know use which, `RunProcess` or `Run` or `StartProcess` or may something else? So I use `Run` since it's available from `v1.0`, and here stringjoin is safe.

3. rename the function/varible name if needed.

ref <https://gitee.com/asdasd1dsadsa/ZhiHu-asdasd1dsadsa/blob/master/Article/在WolframEngine中用WolframPlayer显示图像和动态内容.md>

### CODE REVIEW

**Comment by wuyudi** [comment]
image

**Comment by njpipeorgan** [comment]
It looks great, thanks for adding this feature. 

But I do see some small problems in this implementation:
1. Wolfram Player is called within `handleMainLink`. I would suggest putting it in `handleOutput`, e.g. [here](https://github.com/njpipeorgan/wolfram-language-notebook/blob/10335b12226ab262888f7971be2ea7e8476141cf/resources/init.wl#L192C9-L192C9). 
2. `ToBoxes` followed by `FreeQ` is used to detect when Wolfram Player is needed, but it can cause problems when the expression within the packet should not be evaluated. Instead, you may be able to make use of this [`boxes` variable](https://github.com/njpipeorgan/wolfram-language-notebook/blob/10335b12226ab262888f7971be2ea7e8476141cf/resources/init.wl#L179) to do the check. 
3. `DynamicBox` may interact with variables that are outside the box. Is there a way to detect this? You can then notify the user by rendering an error message.

In terms of the TODOs, here are some potential solutions:
1. You can add a configuration [here](https://github.com/njpipeorgan/wolfram-language-notebook/blob/10335b12226ab262888f7971be2ea7e8476141cf/package.json#L118) for users to set the path to wolframplayer
  - Also add the configuration id to the list [here](https://github.com/njpipeorgan/wolfram-language-notebook/blob/10335b12226ab262888f7971be2ea7e8476141cf/src/extension/notebook-config.ts#L49), so that the extension will send its value to the frontend kernel
  - Also add the configuation [here](https://github.com/njpipeorgan/wolfram-language-notebook/blob/10335b12226ab262888f7971be2ea7e8476141cf/resources/init.wl#L50)
  - Even if the user does not provide the path to wolframplayer, you can probably infer this path using the path to the kernel in [`$CommandLine`](https://github.com/njpipeorgan/wolfram-language-notebook/blob/10335b12226ab262888f7971be2ea7e8476141cf/resources/init.wl#L93).
  - What if the path does not point to a correct wolframplayer? It needs to be checked before calling it.
2. Another configuration to be added is whether or not enabling this feature, and it can have values e.g. "All Graphics and Dynamics", "Only 3D Graphics and Dynamics", "Disable". You then detect the environment and see if it is possible to enable it (e.g. in a remote development environment, running wolframplayer probably does not make sense). If your decision is contrary to the user's choice, send a notification to the user so that they will not be surprised. 
5. Right now, `Run` blocks the main link queue or the output queue. You can try wrapping it with `LocalSubmit` to run asynchronously.

**Comment by wuyudi** [comment]
Progress

- [x] Wolfram Player is called within handleMainLink. I would suggest putting it in handleOutput, e.g. [here](https://github.com/njpipeorgan/wolfram-language-notebook/blob/10335b12226ab262888f7971be2ea7e8476141cf/resources/init.wl#L192C9-L192C9).
- [x] ToBoxes followed by FreeQ is used to detect when Wolfram Player is needed, but it can cause problems when the expression within the packet should not be evaluated. Instead, you may be able to make use of this [boxes variable](https://github.com/njpipeorgan/wolfram-language-notebook/blob/10335b12226ab262888f7971be2ea7e8476141cf/resources/init.wl#L179) to do the check.

**Comment by wuyudi** [comment]
- [x] Right now, Run blocks the main link queue or the output queue. You can try wrapping it with LocalSubmit to run asynchronously.

**Comment by wuyudi** [comment]
```
{Ａ,Ｂ,Ｃ}=ReIm@Table[(Sqrt[2] (a^2 b^2 E^(-3 I t) (-1+4 E^(2/3 I (k \[Pi]+6 t)))+a^4 Cos[3 t]-I b^4 Sin[3 t]))/Sqrt[(a^2+b^2) (a^4+14 a^2 b^2+b^4)+(a^2-b^2)^3 Cos[6 t]],{k,0,2}];
Ｍ=(Ａ+Ｂ+Ｃ)/3;
Manipulate[Block[{a=3,b=2,t=$t},Graphics[{{Circle[{0,0},{a,b}]},{Green,Line[{Ａ,Ｂ,Ｃ,Ａ}]},{Red,Line@Table[Ｍ,{t,0.,$t,2Pi/1000}],Disk[Ｍ,0.1]}},PlotRange->1.2Max[a,b]]],{$t,0.,2Pi}]
```

this code has some problem. Didn't figure out why.

**Comment by wuyudi** [comment]
- [x] You can add a configuration [here](https://github.com/njpipeorgan/wolfram-language-notebook/blob/10335b12226ab262888f7971be2ea7e8476141cf/package.json#L118) for users to set the path to wolframplayer
- [x] Also add the configuration id to the list [here](https://github.com/njpipeorgan/wolfram-language-notebook/blob/10335b12226ab262888f7971be2ea7e8476141cf/src/extension/notebook-config.ts#L49), so that the extension will send its value to the frontend kernel
- [x] Also add the configuation [here](https://github.com/njpipeorgan/wolfram-language-notebook/blob/10335b12226ab262888f7971be2ea7e8476141cf/resources/init.wl#L50)
- [x] Even if the user does not provide the path to wolframplayer, you can probably infer this path using the path to the kernel in [$CommandLine](https://github.com/njpipeorgan/wolfram-language-notebook/blob/10335b12226ab262888f7971be2ea7e8476141cf/resources/init.wl#L93).

I use the `$InstallationDirectory`

- [x] Another configuration to be added is whether or not enabling this feature

Currently I only set a boolean value.

**Comment by wuyudi** [comment]
> (e.g. in a remote development environment, running wolframplayer probably does not make sense). If your decision is contrary to the user's choice, send a notification to the user so that they will not be surprised.

I tend to let user decide that, it's too complex to enumerate all situations.

**Comment by asukaminato0721** [comment]
https://github.com/asukaminato0721/mmaplayer

**Pull request closed without merging**
